config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('habit.urls')),
    path('accounts/', include('accounts.urls')),
    # Django reload
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

habit/urls.py
from django.urls import path
from .views import *


app_name = 'habits'
urlpatterns = [
    # User, all the habits in the current day
    path('', HomeView.as_view(), name="home"),

    path('pomodoro/', PomodoroView.as_view(), name="pomodoro"), # pomodoro -> url a llamar desde template

    # Calendar view
    path('<int:pk>/', CalendarView.as_view(), name="calendar"),

    # Create habit
    path('create/', HabitCreateView.as_view(), name="create"),

    # Update habit
    path('<int:pk>/update/', HabitUpdateView.as_view(), name="update"),

    # Delete habit
    path('<int:pk>/delete/', HabitDeleteView.as_view(), name="delete"),
]

habit/models.py
from datetime import datetime
from pytz import timezone

from django.db import models
from django.contrib.auth import get_user_model

from django.conf.global_settings import LANGUAGE_CODE, TIME_ZONE
from utils.models import BaseModel


User = get_user_model()

# Create your models here.
class Habit(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    name = models.CharField(max_length=100)
    description = models.TextField()

    class Meta:
        ordering = ['-created']
    def __str__(self):
        return self.user.username + " - " + self.name


class Daily(models.Model):
    habit = models.ForeignKey(Habit, on_delete=models.CASCADE)
    # Auto now add true makes the field uneditable, 
    # making it impossible to change in Django Admin
    date = models.DateField(blank=True)
    is_active = models.BooleanField(default=True) 

    # Date workaround
    def save(self, *args, **kwargs):
        if not self.date:
            utc = datetime.now()
            tz = timezone(TIME_ZONE)
            today = utc.astimezone(tz)
            self.date = today
        super(Daily, self).save(*args, **kwargs)
    class Meta:
        verbose_name_plural = "Daily habit"

    def __str__(self):
        return str(self.habit) + " - " + str(self.date)

habit/views.py
from datetime import datetime
from pytz import timezone

from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, View, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import get_object_or_404, get_list_or_404

from django.conf.global_settings import LANGUAGE_CODE, TIME_ZONE
from .models import Habit, Daily

utc = datetime.now()
tz = timezone(TIME_ZONE)
today = utc.astimezone(tz)

# Current day
# All the habits of the user in the current day
class HomeView(LoginRequiredMixin, View):
    model = Habit
    template_name = "habits/home.html"


    def get(self, *args, **kwargs):
        context = {}
        queryset = self.model.objects.filter(user=self.request.user)
        context['habits'] = []
        context['today'] = today
        for habit in queryset:
            q = (Daily.objects.filter(habit=habit, date=today, is_active=True))
            context['habits'].append([habit, q])
        return render(self.request, self.template_name, context)

    # Create a daily with the selected habit
    # by checking the box
    def post(self,  *args, **kwargs):
        habit_id = self.request.POST["daily"]
        habit = Habit.objects.get(id=habit_id)
        q = Daily.objects.filter(habit=habit, date=today)
        if not q:
            Daily.objects.create(habit=habit, date=today)
        else:
            q[0].is_active = not (q[0].is_active)
            q[0].save() 

        return redirect('habits:home')

#  Calendar View for specific habit
class CalendarView(LoginRequiredMixin, DetailView):
    model = Habit
    context_object_name = 'habit'
    template_name = 'habits/calendar.html'

    # Get all the days the habit was done
    def get_context_data(self, *args, **kwargs):
        context =  super().get_context_data(*args, **kwargs)
        context['days'] = Daily.objects.filter(habit=self.get_object(), is_active=True)
        return context


class HabitCreateView(LoginRequiredMixin, CreateView):
    template_name = 'habits/create_habit.html'
    model = Habit
    fields = ['name', 'description']

    success_url = reverse_lazy('habits:home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class HabitUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'habits/habit_form.html'
    model = Habit
    fields = ['name', 'description']
    
    success_url = reverse_lazy('habits:home')

class HabitDeleteView(LoginRequiredMixin, DeleteView):
    model = Habit
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('habits:home')

class PomodoroView(TemplateView):
    template_name = "pomodoro/pomodoro.html"

templates/habits/calendar.html
{% extends 'base.html' %}
{% block title %}{{habit.name | capfirst}} Calendar {% endblock title %}

{% block body %}
<div class="container">
    <div class="text-center center" style="background-color: white;">
        <h1>{{habit.name}}</h1>
        <p class="my-2">{{habit.description}}</p>
        <div class="my-4 ">
            <div id="calendar" class="text-capitalize" style="margin-left: 10px; margin-right: 10px; margin-bottom: 10px;"></div>
        </div>
    </div>
</div>

{% endblock body %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function(){
        var calendarUI = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarUI,{
            events: [
                {% for day in days %}
                {
                    title: 'Hecho este dia',
                    start: '{{ day.date | date:"Y-m-d"}}',
                    end: '{{ day.date | date:"Y-m-d" }}',
                },
                {% endfor %} 
            ],
            locale: 'es',
        });
        calendar.render();
    });
</script>
{% endblock scripts %}

templates/habits/create_habit.html
{% extends 'base.html' %}

{% block title %}Crear Habito{% endblock title %}

{% block body %}
<div class="container">
    <div  
    style="border: solid; border-radius: 10px; margin-top: 10px; background-color: #f3f3f3;" class ="mx-5">
            <h1 style="text-align: center;margin-left: 10px;" class="my-3"> Crea tu hábito!!! </h1>
            <form action="#" method="post" class="form-group text-center mx-5">
                {% csrf_token %}
                
                <label>Nombre del Hábito:</label><br>
                <input 
                placeholder="Ingrese el nombre del habito, minimo de 3 caracteres" 
                class="form-control"
                minlength="3" 
                type="text" 
                id="fname" 
                name="name" 
                style="">
                <br>
                <br>
                
                <label>En que consiste el hábito:</label><br>
                <textarea 
                id="Descripcion" 
                name="description"
                placeholder="Ingrese la descripción del habito, minimo de 3 caracteres" 
                minlength="3" 
                type="text" 
                id="Descripcion" 
                style="" 
                class="form-control"
                ></textarea>
                
                <br>
                <br>

                <div class="container mx-auto mx-5" style="">
                    <div class="mx-5">
                        <div class="mx-5">
                        <div class="mx-5">
                            <div class="mx-5">
                                <button class="btn" 
                                type="submit" 
                                style=" color: white; background-color: #457B9D;">Crear</button>
                                <a class="btn" href="{% url 'habits:home' %}" 
                            style=" border-radius: 5px; color: aliceblue; background-color: #1D3557;" > Cancelar </a>
                            </div>
                        </div>
                        </div>
                    </div>

                </div>
                <br>
                <br>
            </form>
        </div>
</div>
{% endblock body %}

templates/habits/habit_form.html
{% extends 'base.html' %}

{% block title %}Editar Habito {{habit.name}} {% endblock title %}

{% block body %}
<div class="container">
    <div  
    style="border: solid; border-radius: 10px; margin-top: 10px; background-color: #f3f3f3;" class ="mx-5">
            <h1 style="text-align: center;margin-left: 10px;" class="my-3"> Edita el habito </h1>
            <form action="#" method="post" class="form-group text-center mx-5">
                {% csrf_token %}
                
                <label>Nombre del Hábito:</label><br>
                <input 
                placeholder="Ingrese el nombre del habito, minimo de 3 caracteres" 
                class="form-control"
                minlength="3" 
                type="text" 
                id="fname" 
                name="name" 
                style="">
                <br>
                <br>
                
                <label>En que consiste el hábito:</label><br>
                <textarea 
                id="Descripcion" 
                name="description"
                placeholder="Ingrese la descripción del habito, minimo de 3 caracteres" 
                minlength="3" 
                type="text" 
                id="Descripcion" 
                style="" 
                class="form-control"
                ></textarea>
                
                <br>
                <br>

                <div class="container mx-auto mx-5" style="">
                    <div class="mx-5">
                        <div class="mx-5">
                        <div class="mx-5">
                            <div class="mx-5">
                                <button class="btn" 
                                type="submit" 
                                style=" color: white; background-color: #457B9D;">Editar</button>
                                <a class="btn" href="{% url 'habits:home' %}" 
                            style=" border-radius: 5px; color: aliceblue; background-color: #1D3557;" > Cancelar </a>
                            </div>
                        </div>
                        </div>
                    </div>

                </div>
                <br>
                <br>
            </form>
        </div>
</div>
{% endblock body %}

templates/habits/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}


{% block body %}
<div class="container d-flex flex-column align-items-center flex-sm-row">
<img class="" src="{% static "Pandita.png" %}" style="width:200px;height:300px; padding:25px; object-fit: cover;">
<div class="container">
    {% comment %} Definitions {% endcomment %}
    {% now "d" as day %}
    {% now "l" as day_name %}
    {% now "F" as month %}
<div class="my-3 center text-center">
    <h1 class="fw-bold">Hoy es {{day_name | capfirst}} {{day}} de {{month | capfirst}}</h1>
</div>
<div class="">
    <h4>
        Hola {{user.username}}, estos son tus habitos {{daily}}
    </h4>
</div>
<div class="center">
    <ul class="list-group">
        {% for habit, daily in habits %}
            <li class="list-group-item">
                <h4>
                <a href="{% url 'habits:calendar' habit.pk %}">{{habit.name}}</a>
                </h4>
                <p>
                <button type="button" class="btn btn-primary" style="background-color: #457B9D;"><a href="{% url 'habits:update' habit.pk %}" class="link-success">Editar</a></button>
                <button type="button" class="btn" style=" border-radius: 5px; color: aliceblue; background-color: #E63946;"><a href="{% url 'habits:delete' habit.pk %}" class="link-danger" >Eliminar</a></button>
                {% comment %} <button type="button" class="btn" style=" border-radius: 5px; color: aliceblue; background-color: #2c6e49;"><a href="/pomodoro/pomodoro.html" class="link-danger" >Pomodoro</a></button> {% endcomment %}
                </p>
                <form name="formCheckbox" action="" method="POST" id="formCheckbox{{forloop.counter}}">
                    {% csrf_token %}
                    <input type="hidden" name="daily" value="{{habit.pk}}"/>
                    <input type="checkbox" class="form-check"  id="checkBox" {% if daily%}checked{% endif %} onchange="document.getElementById('formCheckbox{{forloop.counter}}').submit()">
                </form>
            </li>
        {% empty %}
            <li class="list-group-item">
                <p>Lo sentimos, no tienes habitos. <a href="{% url 'habits:create' %}" class="link" style="color: Blue;">Crea uno!</a></p>
            </li>   
        {% endfor %}
        
    </ul>
</div>
<style type="text/css">
    .list-group-item{
        padding: 1rem 3rem;
        border: solid 2px #1d3557;
        margin: 0.1rem 0rem;
    }
    h4 a {
        color: #1d3557;
    }
    h4 a:hover {
        color: #457b9d;
    }
    a {
        color: white;
    }
    a:hover {
        color: #c7cee7
    }
    .list-group-item form {
        float: right;
        margin-right: 5%;
        margin-top: -5%;
    }
</style>
</div>
</div>
{% endblock body %}