config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('habit.urls')),
    path('accounts/', include('accounts.urls')),
    # Django reload
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

habit/urls.py
from django.urls import path
from .views import *


app_name = 'habits'
urlpatterns = [
    # User, all the habits in the current day
    path('', HomeView.as_view(), name="home"),

    path('pomodoro/', PomodoroView.as_view(), name="pomodoro"), # pomodoro -> url a llamar desde template

    # Calendar view
    path('<int:pk>/', CalendarView.as_view(), name="calendar"),

    # Create habit
    path('create/', HabitCreateView.as_view(), name="create"),

    # Update habit
    path('<int:pk>/update/', HabitUpdateView.as_view(), name="update"),

    # Delete habit
    path('<int:pk>/delete/', HabitDeleteView.as_view(), name="delete"),
]

utils/models.py
from django.db import models

# Create your models here.
class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Can't create database model with it
    class Meta:
        abstract = True

    def __str__(self):
        return self.name

utils/views.py
from django.shortcuts import render

# Create your views here.

templates/utils/navbar.html
<style>
  .hover-effect:hover {
    opacity: 0.5;
    transition-duration: 0.5s;
  }
</style>

<nav class=" mb-4 navbar navbar-dark navbar-expand-lg bg-dark">
    <a class="navbar-brand fw-bolder hover-effect" href="{% url 'habits:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse py-2" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ">
        <li class="nav-item">
          <a
            class="nav-link active hover-effect"
            aria-current="page"
            href="{% url 'habits:create' %}"
            >Crear Habito 🔥</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link active hover-effect"
            aria-current="page"
            href="{% url 'habits:pomodoro' %}"
            >Pomodoro 🍅</a
          >
        </li>
      </ul>
      <div class="md">
        {% if user.is_authenticated %}
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" 
            type="button" id="dropdownMenuButton" 
            data-toggle="dropdown" 
            aria-haspopup="true" 
            aria-expanded="false">

              Hola {{user.username}}
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="width: 4px">
              <a class="dropdown-item" href="{%url 'accounts:logout' %}" >Salir</a>
            </div>
          </div>

        {% else %}
        <a class="btn btn-danger" href="{% url 'accounts:login' %}">Entra</a>
        {% endif %}
      </div>
    </div>

  <style type="text/css">
    .navbar {
      background: rgb(80,111,120);
      background: linear-gradient(180deg, rgba(80,111,120,1) 85%, rgba(159,219,236,1) 100%);
    }
  </style>
</nav>